* comprof
A simple command timing tool. I like my judgements to have objective substance to them, and one judgement I often find myself interested in making is how efficient a command is. The standard POSIX utility =time= is not very good for this since it only runs its given command once, immediately demanding extra work just to uphold one of the most fundamental and ubiquitus inconsistencies: run-to-run variance. comprof will run your commands any number of times! Brilliant, right?

Options:
- =-t=: how many times to run the command before reporting the average performance
- =-s=: how many seconds to wait between running the command
- =-h=: print help
- =-e=: don't stop even if the command errors out

* Installation
I believe that the executable generated by SBCL is at the very least portable between machines of the same OS and instruction set. I have included a binary for Linux/amd64. If you happen to be one of the many people with a machine which does not match this spec, you'll have to handle installing [[https://www.sbcl.org/platform-table.html][SBCL]] and setting up [[https://www.quicklisp.org/beta/#installation][Quicklisp]] yourself, but after that you can make use of the included Makefile: =make && make install=.
If you've not got a =make= I recommend you contact the developers or maintainers of your system and suggest they include it, then simply use the SBCL compilation command from the Makefile and copy the resultant executable to a convenient location. Alternatively, switch to a system which comes with a =make=.
